version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - nuxt
      - strapi
    ports:
      - 80:80
      - 443:443
    restart: always
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./server:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    restart: always
  nuxt:
    build: ./
    container_name: front-nuxtjs
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm i &&  npm run dev"
    volumes:
      - ./client:/srv/client
    depends_on:
      - strapi
    links:
      - strapi
